luciusDXL/TheForceEngine

- TheForceEngine/TFE_Asset/modelAsset_jedi.cpp
- TheForceEngine/TFE_Asset/modelAsset_jedi.h
- TheForceEngine/TFE_Jedi/Renderer/RClassic_GPU/modelGPU.cpp
This set of changes  does the following:
- remove the hardcoded object limit from the modelGPU rendering system (fixes #203), replaces it with dynamic allocation and freeing of objects.
Additionally, since I was staring at this code:
- static-ize all internally-used functions, which, at least with gcc, results in slightly smaller code.
- get rid of all but one of the containers for the model lists: replace the indices used with pointers to the objects themselves. 
- pack the state of the model building into a struct which is then passed around the user functions.
EDIT: reworded since more changes were added after the original commit.
> RClassic_GPU: modelGPU refinements

- CMakeLists.txt
- remove the "VERSION" tag, it's unused and always out of date anyway.
- Linux: raise minimum version requirements for RtAudio and RtMidi to the versions actually used during testing of the port.  No advantage in supporting outdated and untested versions.
> Linux: update CMake

- TheForceEngine/TFE_DarkForces/hud.cpp
This bandaid fixes missing rendering of font glyphs with index >= 128, fixes missing german Umlaute characters.
Fixes #210 
EDIT: the issue is in TheForceEngine/TFE_DarkForces/hud.cpp:1090:   c <= font->maxChar  signed vs. unsigned.
> DF: Hud: fix HUD font rendering for ASCII codes >= 128

- CMakeLists.txt
- CreateGitVersionH.cmake
- TheForceEngine/version.h
Create a gitVersion.h based on current local repo status. Initially only used with linux builds.
Untested on Windows, but works beautifully with my linux builds.
> CMake/Linux: create gitVersion.h during configure run

- TheForceEngine/TFE_DarkForces/GameUI/agentMenu.cpp
- TheForceEngine/TFE_DarkForces/GameUI/agentMenu.h
- TheForceEngine/TFE_DarkForces/GameUI/escapeMenu.cpp
- TheForceEngine/TFE_DarkForces/GameUI/escapeMenu.h
- TheForceEngine/TFE_DarkForces/GameUI/missionBriefing.cpp
- TheForceEngine/TFE_DarkForces/GameUI/missionBriefing.h
- TheForceEngine/TFE_DarkForces/darkForcesMain.cpp
- TheForceEngine/TFE_DarkForces/gameMessage.cpp
- TheForceEngine/TFE_DarkForces/gameMessage.h
- TheForceEngine/TFE_DarkForces/hud.cpp
- TheForceEngine/TFE_DarkForces/util.h
Other language versions of DF use different keys in the Briefing, Agent, and Escape Menu screens.
Parse the "HOTKEYS.MSG" file which is different for each language version to get to know the right
hotkeys to use.
Fixes #212
> DF: implement Keyboard keys for other languages

- TheForceEngine/TFE_Audio/midiDevice.cpp
- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
- the midi device list only showed the first entry, fix that.
- upon selecting a different midi port, close the open connection first. Gets rid of an error I see on Linux.
Should fix #200 and make #171 irrelevant.
> fix MIDI device list and selection

- TheForceEngine/TFE_Audio/midiDevice.cpp
- TheForceEngine/TFE_Audio/midiDevice.h
- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
The previous MIDI fix was not thorough enough:
- only change the selected device if the combobox had an activity. basically every frame the selected midi device would be reset back to index 0 when no selection was made in the combobox.
- Add a function to get the currently selected midi port so the combobox can show that.
Fixes #226 and #151
> MIDI: more fixes for multiple midi devices

- README.md
- TheForceEngine/TFE_FileSystem/fileutil-posix.cpp
- TheForceEngine/TFE_FileSystem/paths-posix.cpp
- Add step-by-step instructions on how to build and instal TFE Linux from source. Fixes #231 
- change directory/file enumeration to not treat symlinks as special: Fixes #229 
- make all file/dir existence checks case-agnostic: Since DF and Outlaws are DOS/Windows applications, they are used to case-agnostic filesystems, so the linux implementation must do the extra steps to be so as well (noticed because I could not select the "Outlaws.lab" file).
> Linux: misc fixes

- CMakeLists.txt
It contains the adjustable HUD Mod, which was not installed by default and caused crashes before lucius fixed the code.
> Linux/CMake: also install the Mods folder from source

- TheForceEngine/TFE_FileSystem/paths-posix.cpp
Unconditionally (not only in debug builds) look for support data in the executable directory too.
Makes it easier to create a windows-style all-files-in-one-subfolder style installation package.
> Linux/Paths: look for support data in executable directory too.

- CMakeLists.txt
- README.md
- TheForceEngine/TheForceEngine.desktop
Call the final executable on Linux "theforceengine", just like on Windows, for consistency on all supported platforms. The old name "tfelnx" doesn't make it immediately obvious what is is about...
> Linux: name executable "theforceengine"

- TheForceEngine/TFE_Jedi/IMuse/imuse.cpp
Sometimes the priority computed is larger than the allowed 127 by MiDi, and this confuses the Linux ALSA MIDI Parser.  Ensure it's never larger than 127.
Fixes a ton of "incomplete message!" MIDI errors in the log when System Midi is in use on Linux.
> IMuse: clamp priority parameter to 127

- TheForceEngine/TFE_System/CrashHandler/crashHandlerLinux.cpp
Slightly improve the linux crash handler:
- print signal information
- print a backtrace if possible
- avoid own signal handling when being run under debuggers/tracers/...
> Linux: improve crash handler

- TheForceEngine/TFE_A11y/accessibility.cpp
- TheForceEngine/TFE_A11y/accessibility.h
- Fix A11y system not distinguishing between captions and subtitles (by restoring code I had accidentally removed while refactoring)
- Caption/subtitle timing is now measured in microseconds instead of milliseconds to fix timing issues at very high framerates
> Accessibility fixes

- TheForceEngine/TFE_A11y/accessibility.cpp
- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
Fix the following warnings emitted by gcc/clang:
warning: format not a string literal and no format arguments [-Wformat-security]
Since the ImGui::LabelText functions behave like printf(), add an explicit format specifier.
> Fix gcc/clang warnings wrt. varargs in ImGui use

- TheForceEngine/TFE_Jedi/Level/levelBin.cpp
The cstring header was missing, therefore memcpy, memset, strcasecmp, strcat and strcpy could not be found during compilation.
> Fix the build process on GNU/Linux systems.

- TheForceEngine/TFE_A11y/accessibility.cpp
- TheForceEngine/TFE_FileSystem/filestream-posix.cpp
- TheForceEngine/TFE_FileSystem/fileutil-posix.cpp
- TheForceEngine/TFE_FileSystem/fileutil.cpp
- TheForceEngine/TFE_FileSystem/fileutil.h
- TheForceEngine/TFE_FileSystem/paths-posix.cpp
- Extend the mapSystemPath() call to also work on paths, as required by A11y components
- Fix a too small path buffer which causes startup crashes (#327)
> Fix Linux crash in A11y on startup

- TheForceEngine/TFE_DarkForces/config.cpp
- TheForceEngine/TFE_DarkForces/config.h
- TheForceEngine/TFE_DarkForces/mission.cpp
- TheForceEngine/TFE_DarkForces/player.cpp
- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
- TheForceEngine/TFE_Settings/settings.cpp
- TheForceEngine/TFE_Settings/settings.h
Headwave gives some players motion sickness, so this now appears as a setting under "motion sickness" in the Accessibility menu. The setting can still be toggled with F6, but now is saved between sessions.
> Headwave is now a persistent setting in the A11y menu.

- TheForceEngine/TFE_A11y/accessibility.cpp
- TheForceEngine/TFE_A11y/accessibility.h
- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
- TheForceEngine/TFE_Settings/settings.h
- If none of the caption modes are enabled when TFE starts, we now skip the caption initialization process. Captions will be initialized if the user navigates to the Accessibility menu.
- Improved UI layout for Accessibility settings menu; fixed issue where the example caption was obscuring some settings on small screens.
- Restored functionality that adjusts the maximum number of caption lines during cutscenes based on the selected font size.
> A11y: Don't init captions if they are disabled; improved settings UI

- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
> frontEndUi.cpp: On Game Settings screen, fixed green text getting cut off 

- CMakeLists.txt
- README.md
- TheForceEngine/TFE_Audio/CMakeLists.txt
- TheForceEngine/TFE_Audio/midiDevice.h
- TheForceEngine/TFE_Audio/midiPlayer.cpp
- TheForceEngine/TFE_Audio/midiPlayer.h
If RtMidi library is not found on build system, the System Midi music device will not be build (SF2 and OPL3 will still be available) and the final binary will not require RtMidi at all.
This could be useful for flatpatk/snap and SteamDeck builds since it gets rid of an external dependency.
> Linux/CMake: make RtMidi optional

- TheForceEngine/TFE_A11y/accessibility.cpp
- TheForceEngine/TFE_Audio/MidiSynth/soundFontDevice.cpp
- TheForceEngine/TFE_DarkForces/darkForcesMain.cpp
- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
Fix up some paths to make Captions, Soundfonts and Manual/Credits work again on Linux when not running from the build directory.
fixes #309
> Fixup path expectations for Linux

- TheForceEngine/TFE_Audio/midiPlayer.cpp
if an invalid midi-system ID is passed in (e.g. via config file), TFE only complains about it, but this will lead to a crash as soon as the midi device is queried (either Sound settings page or game).
Install the OPL3 device as fallback.
> MidiPlayer: select OPL3 as default midi device

- CMakeLists.txt
- README.md
- TheForceEngine/TFE_Asset/imageAsset.cpp
- TheForceEngine/TFE_Asset/imageAsset.h
- TheForceEngine/TFE_Asset/textureAsset.cpp
- TheForceEngine/TFE_Editor/levelEditor.cpp
- TheForceEngine/TFE_Editor/levelEditorData.cpp
- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
- TheForceEngine/TFE_FrontEndUI/modLoader.cpp
- TheForceEngine/TFE_Game/reticle.cpp
- TheForceEngine/TFE_Game/saveSystem.cpp
- TheForceEngine/TFE_RenderBackend/Win32OpenGL/screenCapture.cpp
- TheForceEngine/TFE_Ui/markdown.cpp
First draft of replacing use of devIL with SDL-image.
Again, main motivation is that SDL-image is much more common, while devIL is more niche (TFE is the only user I know of so far).
This first draft just tries to replace devIL. However, I'd like to replace the TFE_Image::Image struct with SDL_Surface: SDL2 uses it extensively, and it has all the info in "struct Image" plus more.
@luciusDXL: what do you think?
This snapshot already works, only minor issue so far is that the image in a savegame made after this patch is upside down.
> Replace devIL with SDL2_image

- TheForceEngine/TFE_FileSystem/fileutil-posix.cpp
PATH_MAX is canonically provided by limits.h
On some systems, like the ones with GLIBC, it just happens that `dirent.h` also includes a header that defines it.
> Include limits.h in fileutil-posix for PATH_MAX

- CMakeLists.txt
Some distros decide to package the sdl2-image header files separate from the sdl2 main header directory.
And it's the right thing to do anyway.
Fixes #351
> CMake: add SDL2-Image include directory

- TheForceEngine/TFE_Audio/midiPlayer.cpp
- TheForceEngine/TFE_Audio/midiPlayer.h
- TheForceEngine/TFE_Audio/systemMidiDevice.cpp
- TheForceEngine/TFE_Audio/systemMidiDevice.h
- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
- Bring back the midiPlayer::suspend/resumeThread() functions.  While POSIX cannot really suspend a thread like windows can, we can effectively block the midi thread by acquiring the lock: this way the thread can complete it's work and won't run until the lock is released.  Should fix lucius' windows crash when switching the midi device.
- introduce a "(Disabled)" device at index 0: RtMidi tends to spam the log with error messages about writing to non-existing ports. This device is always present and moves all bits to /dev/null.
One can then add and remove midi synthesizers on the fly and they'll show up in the settings screen.
> MIDI fixes

- CMakeLists.txt
- TheForceEngine/TFE_Audio/MidiSynth/soundFontDevice.cpp
- TheForceEngine/TFE_DarkForces/Actor/phaseTwo.cpp
- fix a buffer overrun in the SF2 midi device (Path handling)
- fix a copy-paste error in DF/Actor/phaseTwo (LTO complains about this)
- enable auto-var-zeroing for cmake release builds if compiler supports it (gcc/clang), should fix issues like #363
> Misc Fixes

- TheForceEngine/TFE_DarkForces/player.cpp
- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
- TheForceEngine/TFE_Settings/settings.cpp
- TheForceEngine/TFE_Settings/settings.h
Adds a new A11y setting to disable illumination around the player caused by firing the player's weapons. May improve the player experience for players with photosensitive epilepsy or other conditions aggravated by flashing lights.
> A11y: added a new setting to disable player weapon lighting

- CMakeLists.txt
Remove the use of this flag for now, since gcc DCEs apparently the landru midi code altogether with this.
Fixes #369
> CMake: Revert compiler flag for auto-var-init

- CMakeLists.txt
- TheForceEngine/TFE_DarkForces/Landru/lmusic.cpp
Proper codefix for #369:
- fix the actual bug in the Landru lmusic code
- revert #371, as it can now be enabled again safely (well, ...)
> Fix 369 properly

- TheForceEngine/TFE_RenderBackend/Win32OpenGL/renderBackend.cpp
- TheForceEngine/TFE_RenderBackend/Win32OpenGL/renderTarget.cpp
The current code does functionally a [noop](https://en.wikipedia.org/wiki/NOP_(code) "NOP (code)") but not effectively. Hence, it still costs cycles. This PR does not fix visibly anything but finally does what was originally intended. We get our electron’s worth. :wink:
Btw, clearing color buffers is quite expensive while gaining very little. It is best to avoid doing it. On the other hand, zeroing Z buffers on modern GPUs is very fast.
> [Fix] Clear color buffers with opaque black instead of transparent black (noop)

- TheForceEngine/TFE_RenderBackend/Win32OpenGL/renderBackend.cpp
This patch adds a workaround to make GLEW initialize successfully on wayland, allowing the force engine to work properly when using wayland on linux, more information and existing workarounds can be found on the following issue:
https://github.com/nigels-com/glew/issues/172
I'm not sure if this kind of workarounds are desired, so feel free to close this PR if you have no desire for such a thing!
> Added workaround for GLEW on wayland

- TheForceEngine/TFE_Jedi/Level/rsector.cpp
Change function name from sector_canWallMove to sector_isWallBlockedByPlayer
I assume the name is one that you chose during RE and didn't come from the actual LEC code
I was just finding it a bit difficult to reason about what the function does with its existing name :-) 
An even more accurate name would probably be isMovingWallBlockedByPlayer (or isWallMovementBlockedByPlayer) but that's getting a bit long, happy for you to decide!
> Change function name

- TheForceEngine/TFE_Jedi/InfSystem/infSystem.cpp
- TheForceEngine/TFE_Jedi/Level/rsector.cpp
- TheForceEngine/TFE_Jedi/Level/rsector.h
As discussed in discord
https://discord.com/channels/799331202821521458/911332436707774535/1221183710733406208
The function & variable names for the morph_move and morph_spin elevators will now mirror each other.
> Rename functions and variables for consistency & code readability

- CMakeLists.txt
- ProjectStructure.md
- README.md
- TheForceEngine/Mods/TFE/AdjustableHud/CMakeLists.txt
- TheForceEngine/io.github.theforceengine.tfe.Mod.AdjustableHud.metainfo.xml
- TheForceEngine/io.github.theforceengine.tfe.metainfo.xml
Improves the life of package maintainers and paves the way for integrated mod distribution.
Conceptually, building the “AdjustableHud” mod should have been its own CMake target. But, since CMake is conceptually flawed in general and thus custom build target support in CMake is either incomplete or just a disgrace to implement, we have to go the ugly route of adding build configuration options. Yes, it is ugly but it works and is obviously so intended by CMake devs.
> Enable separate building and packaging of TFE and the “AdjustableHud” mod

- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
- TheForceEngine/TFE_Jedi/Level/rsector.cpp
- TheForceEngine/TFE_Settings/settings.cpp
- TheForceEngine/TFE_Settings/settings.h
This will cause the player to collide with a "solid" adjoined wall that is moving or rotating
Results in a fix for maps like Harkov and Dark Tide 3 which feature a morph_move or morph_spin elevator surrounded by "solid" adjoined walls to simulate riding in a vehicle
> New optional setting: observe "solid wall" flag when testing if object overlaps a wall

- CMakeLists.txt
- TheForceEngine/TFE_Audio/audioDevice.cpp
- TheForceEngine/TFE_Audio/systemMidiDevice.cpp
- TheForceEngine/TFE_DarkForces/gameMusic.cpp
- TheForceEngine/TFE_Editor/LevelEditor/levelEditorData.cpp
- TheForceEngine/TFE_Editor/LevelEditor/levelEditorInf.cpp
- TheForceEngine/TFE_Game/igame.cpp
- TheForceEngine/TFE_Jedi/IMuse/imDigitalSound.cpp
- TheForceEngine/TFE_Jedi/InfSystem/infSystem.cpp
- TheForceEngine/TFE_Jedi/Level/level.cpp
- TheForceEngine/TFE_Jedi/Level/levelData.cpp
- TheForceEngine/TFE_Jedi/Math/core_math.h
- TheForceEngine/TFE_Memory/memoryRegion.cpp
- TheForceEngine/TFE_Memory/memoryRegion.h
- TheForceEngine/TFE_RenderShared/lineDraw2d.cpp
- TheForceEngine/TFE_RenderShared/quadDraw2d.cpp
- TheForceEngine/TFE_Settings/settings.cpp
More bug/warningfixes and updates, also to get it building on Apple/Clang toolchains.  based on feedback in #90 
- QUAD_MAX is a reserved symbol in xnu's "limits.h" file
- clang doesn't like passing std::string to logWrite()
- disable clang's excessive warnings about unhandled enum values in switch() statements
- fix lots of clang warnings about assignments inside while() without extra brackets.
- adjust the min/max/clamp(size_t) functions to u64, since size_t == u32 on 32bit targets
- LINE_MAX is another reserved symbol on xnu/apple.
- change the size_t in memoryRegion, which is written out to savegames, to an u64, to keep apple toolchain happy and the savegame format independent of the target architecture size.
- rename the "\<autoselect\>" audio device to "System Default", and change …
> More bugfixes/improvements

- TheForceEngine/main.cpp
Set the "Application Name" SDL Hint.  This fixes a cosmetic issue on at least Linux wrt. to the audio stream name when pipewire/pulseaudio are used as sound servers (before/after):
> Set Application name SDL Hint

- TheForceEngine/TFE_Jedi/IMuse/imDigitalSound.cpp
In Dark Tide 1, there's the MCHN3.VOC file which contains a voc chunk with id 2, which causes TFE to spam the log with an unending stream of:
```
[Error : iMuse] ERR: Illegal chunk in sound    2561ba3c54df0...
[Error : iMuse] ERR: Illegal chunk in sound    3561ba3cb5658...
[Error : iMuse] ERR: Illegal chunk in sound    5561ba3cb5658...
```
Fix this by handling type 2 chunks.
Also clarify the debug output a bit and stop spamming the log on known but unhandled chunks (3 and 5).
In DT1, there's also the "BUBBLS1.VOC" file which has only 1 chunk but its size is too small, doesn't cover the entire file. This will cause a one-time log entry
```
[Error : iMuse] ERR: Illegal chunk 170 in sound 657844099906576...
```
> IMuse: handle type 2 VOC  chunks

- TheForceEngine/io.github.theforceengine.tfe.metainfo.xml
This will reduce the maintenance load over here; I'll maintain the releases.xml in the flathub repo along with the updates over there.
> Use external release metadata XML for Flathub info

- TheForceEngine/TFE_DarkForces/darkForcesMain.cpp
- TheForceEngine/TFE_Editor/LevelEditor/userPreferences.cpp
- TheForceEngine/TFE_Settings/gameSourceData.h
- TheForceEngine/TFE_Settings/settings.cpp
- TheForceEngine/main.cpp
More little things encountered so far:
*  move the sdl2main.lib #pragma under the _WIN32 ifdef, because the lld linker on not-windows adheres to it
* Abort DF launch early if not all GOBs can be found, to avoid a crash later. Found while playing with flatpak.
* address a new -Wformat-security warning in the Editor code
* constify the pointers in the game source data header even more to fix a broken lld, fixes #430, although in my opinion this is a problem with the OPs linker, not TFE, but the fix is harmless.
> More little fixes

- TheForceEngine/TFE_Asset/levelObjectsAsset.cpp
- TheForceEngine/TFE_Asset/levelObjectsAsset.h
- TheForceEngine/TFE_Asset/logicTypes.h
- TheForceEngine/TFE_DarkForces/Actor/actor.cpp
- TheForceEngine/TFE_DarkForces/Actor/actorSerialization.cpp
- TheForceEngine/TFE_DarkForces/Landru/ldraw.cpp
- TheForceEngine/TFE_DarkForces/animLogic.cpp
- TheForceEngine/TFE_DarkForces/generator.cpp
- TheForceEngine/TFE_DarkForces/hitEffect.cpp
- TheForceEngine/TFE_DarkForces/logic.cpp
- TheForceEngine/TFE_DarkForces/projectile.cpp
- TheForceEngine/TFE_DarkForces/sound.cpp
- TheForceEngine/TFE_DarkForces/updateLogic.cpp
- TheForceEngine/TFE_DarkForces/vueLogic.cpp
- TheForceEngine/TFE_Jedi/InfSystem/infState.cpp
- TheForceEngine/TFE_Jedi/InfSystem/infSystem.cpp
- TheForceEngine/TFE_Jedi/InfSystem/message.cpp
- TheForceEngine/TFE_Jedi/Level/level.cpp
- TheForceEngine/TFE_Jedi/Level/levelData.cpp
- TheForceEngine/TFE_Jedi/Level/robjData.cpp
- TheForceEngine/TFE_Jedi/Level/rtexture.cpp
- TheForceEngine/TFE_Jedi/Memory/allocator.cpp
- TheForceEngine/TFE_Jedi/Renderer/RClassic_GPU/modelGPU.cpp
- TheForceEngine/TFE_Jedi/Renderer/RClassic_GPU/rsectorGPU.cpp
- TheForceEngine/TFE_Jedi/Renderer/RClassic_GPU/screenDrawGPU.cpp
- TheForceEngine/TFE_RenderShared/modelDraw.cpp
- TheForceEngine/TFE_RenderShared/triDraw3d.cpp
While building with -flto and gcc on Linux does succeed, the resulting binary crashes early during sound loading due to the Allocator returning nullptrs.  This set of 3 patches removes all warnings emitted by GCC during the LTO run, and the resulting binary actually works fine as well (played a few levels, mods, saved/loaded savegames from both the lto-patched and vanilla binary, no issues whatsoever).
Comparison of binary size (-O3 -march=znver4):
```
text    data     bss     dec     hex filename
5754171   84401 3355328 9193900  8c49ac theforceengine-gcc15
4317669   48488 3215256 7581413  73aee5 theforceengine-gcc15-lto
```
Size reduction of 1.54MiB or ~17,5%
The thing that LTO was most confused by is apparently the wraparound-to-nullptr design in the TFE_Jedi Allocator,  I changed it a …
> Fixes for GCC LTO (Link Time Optimizations)

- TheForceEngine/TFE_A11y/accessibility.h
- TheForceEngine/TFE_DarkForces/mission.cpp
- TheForceEngine/TFE_DarkForces/mission.h
- TheForceEngine/TFE_DarkForces/player.cpp
- TheForceEngine/TFE_DarkForces/player.h
- TheForceEngine/TFE_Settings/settings.cpp
- TheForceEngine/TFE_Settings/settings.h
> Mod conf overrides

- TheForceEngine/TFE_DarkForces/GameUI/pda.cpp
- TheForceEngine/TFE_DarkForces/automap.cpp
- TheForceEngine/TFE_DarkForces/automap.h
> Adding Mouse panning to the PDA

- TheForceEngine/TFE_DarkForces/darkForcesMain.cpp
As discussed in discord
https://discord.com/channels/799331202821521458/799332995373989888/1298733816860643490
As you recommended, I've put the mod path first in the list so things will get loaded from there ahead of other paths; hopefully this is what we want.
> Add mod directory to s_searchPaths when loading from a custom GOB

- TheForceEngine/TFE_FrontEndUI/modLoader.cpp
- TheForceEngine/TFE_System/system.h
Add open folder buttons in the mod section.
> Adding open folder button for mods.

- TheForceEngine/TFE_DarkForces/player.cpp
Otherwise with cheats slow you down.
> Make sure we can fly over water sectors.

- TheForceEngine/TFE_DarkForces/generator.cpp
@mlauss2 discovered that the existing code crashes with gcc-14/15
I've replaced std::string with char[] as per his recommendation
note- the source variable (s_objSeqArg2) is has  a length of 256
> Custom logics fix

- TheForceEngine/TFE_DarkForces/player.cpp
- TheForceEngine/TFE_DarkForces/player.h
- TheForceEngine/TFE_DarkForces/sound.cpp
- TheForceEngine/TFE_DarkForces/vueLogic.cpp
- TheForceEngine/TFE_Jedi/Renderer/jediRenderer.cpp
The (previously unused) camera transform did not calculate pitch, and did not copy pitch to the transformed object. 
It was just set at 0
> Fix VUE camera

- TheForceEngine/ExternalData/DarkForces/pickups.json
- TheForceEngine/TFE_DarkForces/agent.cpp
- TheForceEngine/TFE_DarkForces/darkForcesMain.cpp
- TheForceEngine/TFE_DarkForces/hud.cpp
- TheForceEngine/TFE_DarkForces/item.cpp
- TheForceEngine/TFE_DarkForces/item.h
- TheForceEngine/TFE_DarkForces/pickup.cpp
- TheForceEngine/TFE_DarkForces/pickup.h
- TheForceEngine/TFE_DarkForces/player.cpp
- TheForceEngine/TFE_DarkForces/player.h
- TheForceEngine/TFE_DarkForces/weaponFireFunc.cpp
- TheForceEngine/TFE_ExternalData/pickupExternal.cpp
- TheForceEngine/TFE_ExternalData/pickupExternal.h
- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
- TheForceEngine/TFE_Jedi/Level/robjData.h
- TheForceEngine/TFE_Jedi/Level/rsector.cpp
- TheForceEngine/TheForceEngine.vcxproj
- TheForceEngine/TheForceEngine.vcxproj.filters
As was done with projectiles and effects, I've externalised pickups data to a JSON.
The first commit in this PR renames a number of constants and variables to more accurately reflect what they are.
> Externalise pickups

- TheForceEngine/TFE_DarkForces/item.cpp
Hi Lucius, can I please put in this small amendment.
Now that the data is externalised, it is possible that someone can attempt to list a different kind of asset (eg. BM or 3DO) which may cause a crash
I saw one of our modder friends on Discord try it already :-) 
So I think we should block that by ensuring `getFrame()` is only called on a FME
> Check for FME extension before attempting to load a FME

- TheForceEngine/ExternalData/DarkForces/weapons.json
- TheForceEngine/TFE_ExternalData/weaponExternal.cpp
Realised that I made a small mistake here.
I made ammoEnergy the default ammo (instead of nullptr), to prevent the game from crashing if `weapons.json` is malformed
But for fists, the ammo needs to be nullptr
> Fix for fist ammo

- TheForceEngine/TFE_ExternalData/pickupExternal.cpp
- TheForceEngine/TFE_ExternalData/weaponExternal.cpp
This is intended to fix the issue where the ext data files could not  be loaded from outside of the build directory on linux machines
> Fix external data path mapping on linux machines

- README.md
Hi,
just noticed this while trying to build TFE. Maybe you are interested. Thanks.
DISABLE_SYSMIDI seems to have been migrated to ENABLE_SYSMIDI in https://github.com/dedeibel/TheForceEngine/commit/da751a97a27a585f77cc168aa53c5e0a6476d6ce and auto discovery has been implemented
> Update README.md remove mention of DISABLE_SYSMIDI

- TheForceEngine/TFE_Game/saveSystem.cpp
This is a fix for #521 . You will no longer reset the mission if you are missing the quicksave.
> Fix for quickload bug #521

- TheForceEngine/TFE_DarkForces/Scripting/gs_player.cpp
- TheForceEngine/TFE_DarkForces/player.cpp
- TheForceEngine/TFE_DarkForces/player.h
- TheForceEngine/TFE_Jedi/Level/robjData.h
The motive of this is to support the feature I am creating which allows the camera (eye) to be switched between the player object and other objects.
I want to be able to stop the player from moving while (for example) a cinematic sequence is playing and the eye is elsewhere.
I've allowed separate control over movement, rotation and firing so that modders can have fine-tuned control. Someone might want to suppress firing while still allowing movement, and so on.
> Add ability to disable player movement/rotation/fire via scripting

- TheForceEngine/TFE_DarkForces/Scripting/gs_level.cpp
- TheForceEngine/TFE_DarkForces/Scripting/gs_level.h
- TheForceEngine/TFE_Jedi/InfSystem/message.cpp
- TheForceEngine/TFE_Jedi/InfSystem/message.h
- TheForceEngine/TFE_Jedi/Level/levelData.cpp
- TheForceEngine/TFE_Jedi/Level/levelData.h
- Add method to gs_level API to get a sector by its name 
- serialise the MessageAddresses (sector names) so they will persist after save/load
> Scripting get sector by name

- TheForceEngine/TFE_DarkForces/agent.cpp
- TheForceEngine/TFE_FileSystem/paths-posix.cpp
- TheForceEngine/TFE_FileSystem/paths.cpp
- TheForceEngine/TFE_FileSystem/paths.h
- TheForceEngine/main.cpp
Night Dive stores their DARKPILO.cfg in %USERPROFILE%\Saved Games\Nightdive Studios\Dark Forces Remaster instead of the game folder. This is why when people switch to TFE they lose all their saves. 
Fix for #495
> Fix for remaster darkpilo.cfg which is not located in the game folder.

- TheForceEngine/TFE_DarkForces/player.cpp
This prevents save/load crashes when the player and eye are different objects
A small number of existing mods (like Purple's recent "Enter the dragon" level) do this.
It isn't necessary to validate the eye object because it should never be deleted.  (If it has somehow been deleted, there are FAR bigger issues to worry about!!!)
> Don't validate the eye object when loading a savegame

- TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
Repro: Go to Settings -> Input -> Input Mapping and scroll to the very bottom. The list ends where one can remap Weapon 5.
Weapon 6-10 (last remappable keys in the list) are not displayed because height of the Imgui child isn't sufficient.
> Fix missing input remap entries in Settings GUI (Weapon6-10, Imgui child window height)

- TheForceEngine/TFE_ExternalData/pickupExternal.h
`name` should start off as nullptr
> Fix for external pickups 

- TheForceEngine/TFE_DarkForces/Scripting/gs_game.cpp
- TheForceEngine/TFE_DarkForces/Scripting/gs_level.cpp
- TheForceEngine/TFE_DarkForces/Scripting/scriptObject.cpp
- TheForceEngine/TFE_DarkForces/Scripting/scriptSector.cpp
Add a MessageType enum, including
`MASTER_ON`, `MASTER_OFF`
`NEXT_STOP`, `PREV_STOP`
`WAKEUP`
`CRUSH`
Enable sending messages to sectors and objects
Scripts will be able to affect elevators
Scripts will be able to alert (WAKEUP) or instantly kill (CRUSH) enemies
> Send messages from ForceScript

- TheForceEngine/TFE_Game/saveSystem.cpp
The external data needs to be cleared when loading a save.
I had been relying on the user quitting back to the menu to clear the data.
But you can load a savegame without quitting to the menu!
The result is that if you load a savegame for a mod while a different mod is running (without first returning to the menu), the first mod's weapons/pickup data and custom logics will carry across into second other mod and the second mod's external data won't be loaded.
> Bug fix - external data needs to be cleared out before loading a game
