TheForceEngine/TFE_Archive/archive.h
TheForceEngine/TFE_Jedi/Math/core_math.cpp

Fixes compilation with unreferenced SEEK_SET and std::swap().

Fix compilation on recent VS toolchain

---

README.md

Add some notes about build and runtime requirements for TFE on Linux.  Fixes #208

README: add a few Linux-specific notes.

---

CreateGitVersionH.cmake

If git is not available (git executable not installed, or not a git repository, i.e. release tarball) skip autogeneration of the gitVersion.h file.  In this case the build system will pick up the shipped gitVersion.h, with accurate release version information.

CMake: gitVersion: do nothing if git is not available.

---

TheForceEngine/TFE_Asset/dfKeywords.h

I started out doing this to identify the ones which are un-implemented
But ended up labelling all the INF and logic ones too
Let me know if you think it's helpful. If you'd prefer I can wind it back to just identifying the unimplemented ones

Add comments categorising keywords and noting those which are not implemented

---

TheForceEngine/TFE_FileSystem/fileutil-posix.cpp
TheForceEngine/TFE_FileSystem/fileutil.cpp
TheForceEngine/TFE_FileSystem/fileutil.h
TheForceEngine/TFE_FileSystem/paths-posix.cpp

Consider search paths for case-insensitive search as well.
Fixes #252

Linux: also consider Paths for case-insensitive searching

---

TheForceEngine/TFE_DarkForces/vueLogic.cpp
TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp
TheForceEngine/TFE_Settings/settings.cpp
TheForceEngine/TFE_Settings/settings.h

... making it smooth at high framerates

Added a "Smooth VUEs" option which interpolates VUE motion

---

TheForceEngine/TFE_A11y/accessibility.cpp

Also, don't advance caption timer while console is open, and code cleanup

accessibility.cpp: Updated showCaption console command for microseconds

---

TheForceEngine/Captions/subtitles-de.txt

Transcribed all German voice lines.  I left the unused voice lines untranslated in the file.

German subtitles

---

TheForceEngine/Captions/subtitles-de.txt

"MIENE" (countenance) to "MINE" (mine/pit), this irritated me a lot in Dark Tide 2.
I also changed "Unterbruch" since this is (I think) a Swiss German expression, not commonly heard in Germany or Austria (to "Unterbrechung")

Fix tiny mistakes in german subs

---

.github/workflows/ubuntu-gcc.yml

Adds a github workflow file to build the master branch on every push.

add a Ubuntu build workflow for github

---

TheForceEngine/Captions/subtitles-en.txt

TFW the title of the PR is about 30x as long as the content in the PR.

subtitles-en.txt: Add missing end quote to m01reb02

---

TheForceEngine/TFE_A11y/accessibility.cpp
TheForceEngine/TFE_A11y/accessibility.h
TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp

A11y: added a "Refresh caption/font files" button to settings menu.

---

TheForceEngine/TFE_Editor/AssetBrowser/assetBrowser.cpp
TheForceEngine/TFE_Editor/LevelEditor/Rendering/viewport.cpp
TheForceEngine/TFE_Editor/LevelEditor/browser.cpp
TheForceEngine/TFE_Editor/LevelEditor/entity.cpp
TheForceEngine/TFE_Editor/LevelEditor/levelEditorData.cpp
TheForceEngine/TFE_Editor/editor.cpp
TheForceEngine/TFE_FileSystem/fileutil-posix.cpp

This PR fixes the Editor on Linux: loading of UI_Images/* icons, larger buffers for paths, compiler warning fixes.

Editor: Fix on Linux

---

TheForceEngine/TFE_System/log.cpp

Makes it easier to identify when an event occurred.

Adding logging timestamps

---

TheForceEngine/TFE_Settings/settings.cpp

Make it easier for modders to start counting with 1.

Switch mod conf versioning to 1

---

TheForceEngine/TFE_ExternalData/weaponExternal.cpp

This is a fix required for Linux and other non-windows machines
@mlauss2 have I done this correctly? Thank you.

Change to forward slash for paths

---

TheForceEngine/ExternalData/DarkForces/weapons.json
TheForceEngine/TFE_DarkForces/darkForcesMain.cpp
TheForceEngine/TFE_DarkForces/player.cpp
TheForceEngine/TFE_DarkForces/weapon.cpp
TheForceEngine/TFE_DarkForces/weapon.h
TheForceEngine/TFE_DarkForces/weaponFireFunc.cpp
TheForceEngine/TFE_DarkForces/weaponFireFunc.h
TheForceEngine/TFE_ExternalData/logicTables.cpp
TheForceEngine/TFE_ExternalData/logicTables.h
TheForceEngine/TFE_ExternalData/weaponExternal.cpp
TheForceEngine/TFE_ExternalData/weaponExternal.h
TheForceEngine/TFE_FrontEndUI/frontEndUi.cpp

This is done, but it can wait till after the upcoming release if you would like to investigate those 2 RE bugs further.

Externalise weapons

---

TheForceEngine/TFE_DarkForces/Actor/actor.cpp
TheForceEngine/TFE_DarkForces/Actor/actor.h
TheForceEngine/TFE_DarkForces/Actor/actorInternal.h
TheForceEngine/TFE_DarkForces/Actor/actorModule.h
TheForceEngine/TFE_DarkForces/Actor/animTables.h
TheForceEngine/TFE_DarkForces/Actor/bobaFett.cpp
TheForceEngine/TFE_DarkForces/Actor/dragon.cpp
TheForceEngine/TFE_DarkForces/Actor/enemies.cpp
TheForceEngine/TFE_DarkForces/Actor/exploders.cpp
TheForceEngine/TFE_DarkForces/Actor/flyers.cpp
TheForceEngine/TFE_DarkForces/Actor/mousebot.cpp
TheForceEngine/TFE_DarkForces/Actor/phaseOne.cpp
TheForceEngine/TFE_DarkForces/Actor/phaseThree.cpp
TheForceEngine/TFE_DarkForces/Actor/phaseTwo.cpp
TheForceEngine/TFE_DarkForces/Actor/scenery.cpp
TheForceEngine/TFE_DarkForces/Actor/sewer.cpp
TheForceEngine/TFE_DarkForces/Actor/troopers.cpp
TheForceEngine/TFE_DarkForces/Actor/turret.cpp
TheForceEngine/TFE_DarkForces/Actor/welder.cpp

This PR does **not** change any functionality -- it is for making the Actor code more readable.
"Magic numbers" for various flags are replaced by named enum values.
Comments are added to explain what is happening in the code

Actor code readability amendments

---

CMakeLists.txt
TheForceEngine/TFE_DarkForces/darkForcesMain.cpp
TheForceEngine/TFE_Editor/AssetBrowser/assetBrowser.cpp
TheForceEngine/TFE_Editor/EditorAsset/editorFrame.cpp
TheForceEngine/TFE_Editor/EditorAsset/editorLevelPreview.cpp
TheForceEngine/TFE_Editor/EditorAsset/editorObj3D.cpp
TheForceEngine/TFE_Editor/EditorAsset/editorSound.cpp
TheForceEngine/TFE_Editor/EditorAsset/editorSprite.cpp
TheForceEngine/TFE_Editor/EditorAsset/editorTexture.cpp
TheForceEngine/TFE_Editor/LevelEditor/levelEditorInf.cpp
TheForceEngine/TFE_Editor/editor.cpp
TheForceEngine/TFE_Editor/editorConfig.cpp
TheForceEngine/TFE_Editor/editorLevel.cpp
TheForceEngine/TFE_Editor/editorProject.cpp

Tested on Ubuntu 20.04 with CMake 3.16.3, GCC 9.4.0 and clang 10.0.0.

Fix building on Linux

---

TheForceEngine/TFE_DarkForces/Actor/actor.cpp
TheForceEngine/TFE_DarkForces/Actor/actor.h
TheForceEngine/TFE_DarkForces/Actor/actorInternal.h
TheForceEngine/TFE_DarkForces/Actor/actorModule.h
TheForceEngine/TFE_DarkForces/Actor/actorSerialization.cpp
TheForceEngine/TFE_DarkForces/Actor/exploders.cpp
TheForceEngine/TFE_DarkForces/Actor/flyers.cpp
TheForceEngine/TFE_DarkForces/Actor/scenery.cpp
TheForceEngine/TFE_DarkForces/Actor/sewer.cpp
TheForceEngine/TFE_DarkForces/hitEffect.cpp
TheForceEngine/TFE_DarkForces/hitEffect.h
TheForceEngine/TFE_DarkForces/weaponFireFunc.cpp

As with the previous PR, this one does not add or change any functionality; it is a refactor and tidy up of the actor code
- the return type of Actor module functions and messageFunctions should be Tick, not JBool (the return values are assigned to a nextTick variable)
- a couple of functions have been given more "correct" names
- comments have been added

Actor code refactor part 2

---

TheForceEngine/TFE_DarkForces/pickup.cpp
TheForceEngine/TFE_DarkForces/player.cpp
TheForceEngine/TFE_DarkForces/player.h
TheForceEngine/TFE_DarkForces/projectile.cpp
TheForceEngine/TFE_DarkForces/projectile.h
TheForceEngine/TFE_Jedi/Level/robjData.h
TheForceEngine/TFE_Settings/settings.cpp
TheForceEngine/TFE_Settings/settings.h

This was requested from the community
The new overrides are
- Wall and floor damage
- Gas damage
- Gravity
- Battery consumption rates
- Supercharge duration

Mod-conf overrides for various constants

---

TheForceEngine/TFE_DarkForces/Scripting/gameScripts.cpp
TheForceEngine/TFE_DarkForces/Scripting/gs_level.cpp
TheForceEngine/TFE_DarkForces/Scripting/gs_level.h
TheForceEngine/TFE_DarkForces/Scripting/gs_player.cpp
TheForceEngine/TFE_DarkForces/Scripting/gs_player.h
TheForceEngine/TFE_ForceScript/scriptAPI.h
TheForceEngine/TheForceEngine.vcxproj
TheForceEngine/TheForceEngine.vcxproj.filters

Introduces ability to manipulate the player via scripting
If this can be squeezed into the upcoming release, that would be terrific, but you don't think that's a good idea, that's fine, it can wait for the next one. It's your call to make :-) 
I understand that there are still the issues to sort out re save/load not working properly with scripting

Add GS_Player class

---

TheForceEngine/TFE_DarkForces/Actor/actor.cpp

The veterans in the discord community couldn't think of any mod that exploits this vanilla bug, so if it's ok with you, I'm putting in a non-optional fix
If somebody discovers later that we've ruined an old mod, we could come back and add an option...

Fix the corpse & second height vanilla bug

---

TheForceEngine/TFE_DarkForces/Scripting/gs_game.cpp
TheForceEngine/TFE_DarkForces/Scripting/gs_game.h
TheForceEngine/TFE_DarkForces/agent.cpp
TheForceEngine/TFE_FileSystem/paths-posix.cpp
TheForceEngine/TFE_FileSystem/paths.cpp
TheForceEngine/TFE_FileSystem/paths.h
TheForceEngine/main.cpp

**Note:** This is on top of Darkpilo remaster fix 
Scripting enhancements. 
Add random call 
Add hugText calls

Script enhancements

---

TheForceEngine/TFE_DarkForces/Scripting/gs_player.cpp
TheForceEngine/TFE_DarkForces/Scripting/gs_player.h
TheForceEngine/TFE_DarkForces/Scripting/scriptObject.cpp

Adds the ability to get & set logic data via ForceScript
For now: hitpoints, projectile and velocity

Object Scripting - manipulate logic data
